### ISSUE TITLE
Mongo DB error

### ISSUE THREAD

**Issue by grrminator** [shikhir-arora/karma-simple#11]
Uncaught Promise Error:
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/ubuntu/karma-simple/node_modules/.registry.npmjs.org/mongodb-core/3.1.5/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/home/ubuntu/karma-simple/node_modules/.registry.npmjs.org/mongodb-core/3.1.5/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/home/ubuntu/karma-simple/node_modules/.registry.npmjs.org/mongodb-core/3.1.5/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
[Thu Nov 29 2018 02:02:05 GMT+0000 (Coordinated Universal Time)] [READY] Connected as Mr. House#4316 517492420510744618
[Thu Nov 29 2018 02:02:05 GMT+0000 (Coordinated Universal Time)] Uncaught Promise Error:
Error: Request failed with status code 503
    at createError (/home/ubuntu/karma-simple/node_modules/.registry.npmjs.org/axios/0.19.0-beta.1/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/ubuntu/karma-simple/node_modules/.registry.npmjs.org/axios/0.19.0-beta.1/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/ubuntu/karma-simple/node_modules/.registry.npmjs.org/axios/0.19.0-beta.1/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

What is going on?

**Comment by shikhir-arora** [comment]
Hi, sorry for the delay. Do you have a running MongoDB instance on localhost?

**Comment by grrminator** [comment]
No I'm running on Atlas

**Comment by shikhir-arora** [comment]
You need to login to your Atlas portal and get the connection string. It'll look like `mongodb+srv://c1hkasia-m0f-g085d.azure.mongodb.net/something` and you need to configure a user/password/allow your IP through the config on Atlas's portal.
